### ISSUE TITLE
Hello, nice project !

### ISSUE THREAD

**Issue by GevaudanBeast** [BirchJD/PiOBDII#1]
Hello,
I am not a developer.
I am looking for a project (read OBD information in USB or WIFI) as yours to use it in my car on a Pi Zero W.
This one must manage MotionEye as well as RaspAp.
I wish a display without used GUI (a bit like "htop") for limited resources and that it is readable by a human (no hex).
Is this possible from your project?
Thank you for your reply.

**Comment by BirchJD** [comment]
I have just checked in the start of a GUI coding. If you get the previous check in, it just displays all information in text. It is not code complete and tested, you would need to test if it is suitable for your needs.

**Comment by GevaudanBeast** [comment]
Thank you for your answer, I have not been able to test it yet.
My project (Pi Zero W, based installation Raspbian Stretch) is the realization of a Dashcam (MotionEye) / Hotspot (RaspAP, with 2 wifi) / OBDII player, which will connect to the HDMI input of my car stereo (Pioneer SPH-DA120).
I managed to configure MotionEye, RaspAP.
I encounter some difficulty to broadcast in HDMI (the native format of the screen is 800x480, but I think it is the "conversion" from 720p or 1080p, I must test)
It remains for me to interface the OBII reader (USB or WIFI) and to configure your script "PiOBDII"
Can you confirm that "PiOBDII" only needs a command line console, the Pi Zero W is limited in resource.
THANK YOU and sorry about my english.

**Comment by BirchJD** [comment]
The application now uses graphics, but it doesn't need the desktop version of Raspbian, just the console version is OK. When the python package pygame is installed, it installs the basics it needs to display the graphics.
I have an update this weekend which will add icons and hopefully confirmation dialogs and data selection for the meters. The video this weekend will show it running on a portable device I will be using in my car ultimately, using the Raspberry Pi touch screen which is 800x480. And also using a Bluetooth OBDII dongle.

**Comment by GevaudanBeast** [comment]
Really very cool!

I am Graphic Designer, maybe I "participate" by bringing my knowledge in terms of ergonomics, layout and icon creation (I'm a vector "specialist").

Very good thing for the Bluetooth version, question, is it also possible to provide the WIFI version of the OBDII dongles?

Another detail about the power supply of the Pi Zero, my OBDII dongle is usb, think you can feed on the permanent positive my Raspberry without any harm to the operation of the dongle (I thought I read that it provided about 2A via the OBDII connector) and do you think the dongle is powering the USB and could directly supply power to the Pi Zero?

THANK YOU

**Comment by BirchJD** [comment]
I'm not going to be supporting the code going forward, it's just part of a tool set I will be using to work with my ECU. The graphics in the video I post today, or possibly tomorrow, will pretty much be as far as I take the graphics. I just need to add some scale values and a few things like that. If anyone does want to support it, they are welcome to branch the repository and support their branch.

The Bluetooth dongle just creates a serial port when plugged into the Raspberry Pi, so there is no special release for this, it just has a different string in the config. I haven't seen the wifi one, so I don't know how that does it.

I don't know if it is safe to power anything from the power of a USB device, so I can't advise on that.
