### ISSUE TITLE
FAILED TO INITIALIZE ELM327 DEVICE

### ISSUE THREAD

**Issue by engineer00127** [BirchJD/PiOBDII#3]
I can not connect to my car, the screen just shows
FAILED TO INITIALIZE ELM327 DEVICE.
FAILED TO CONNECT TO ELM327 DEVICE.
my car is Ford Everest 2010 which used CAN (11/500kb)
and I am using Raspberry Pi 3 which already integrated Bluetooth inside so i don't need to use a USB Bluetooth dongle. So i think the serial port that i am using to connect Bluetooth is rfcomm, not USB port.
what do I need to do to make it works, I am not a coder? Please help me !

**Comment by BirchJD** [comment]
If you get the latest code and the following video will show in details how to pair the Bluetooth device and check it is paired:
https://www.youtube.com/watch?v=lHwvoFLbAkM

**Comment by BirchJD** [comment]
From what you sent me, you found the issue appears to be a fake ELM327 device:
https://obd-car-doctor.com/en-us/thread/Attention-Bad-Bluetooth-adapters-/
